### ISSUE TITLE
When use spawn egg to touch floor

### ISSUE THREAD

**Issue by Danding1314** [BlockHorizons/BlockPets#201] opened 2019-04-22 13:40 UTC
[08:38:39] [Server thread/CRITICAL]: RuntimeException: "Tag with name "petOwner" not found and no valid default value given" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 188

Spawn Egg Bug :D

**Comment by Muqsit** [comment] 2019-04-22 17:09
Duplicate of #147

**Closed by Muqsit** 2019-04-22 17:09 UTC
