### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlockHorizons/BlockPets#32] opened 2017-06-16 13:04 UTC
[Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 69

It happens wen player gets attacked by pet. Maybe you can add to focus attack on one player, maybe it happens wen a pet is ganged up, and always change targets? I don't know. Or simply trows error because pet attack?

**Comment by Sandertv** [comment] 2017-06-16 13:05
No, this does not happen when a per gets attacked, it happens when a pet dies. I'm already working on it.

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:07
nope, I was on 1vs1 with my pet, and wen pet hit a player it trows this error (pet invincible)

**Comment by Sandertv** [comment] 2017-06-16 13:08
Maybe you're not using PMMP, a non supported version, or something else, but I cannot reproduce thus. Sorry.

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:25
ya, it happens randomly, I was thinking that if pet hit player it make erros, what about map change? OMG that error confuse me xd.
As long I keep pets just for me there are no problems xD

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:32
I think I know the issue. I attacked a afk player, but pet didn't attack, and I saw the error in console.

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:32
pet attack only if I or he are attacked

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:34
is random, I really don't know. Maybe wen you change map, pet is killed and respawned. I don't know, sorry for spam

**Comment by Sandertv** [comment] 2017-06-16 13:35
Errors don't happen randomly by a map change, that can't be the issue. Looking into it right now.

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:38
i know that because wen i change map, pet change collors,

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:38
llama pet

**Comment by Sandertv** [comment] 2017-06-16 13:39
Yeah that happens for every pet. That's because pets get closed and respawned on the spot you change worlds. That's how it works.

**Comment by TDMidkwhatisxd** [comment] 2017-06-16 13:41
maybe that's the cause of error?

**Comment by Sandertv** [comment] 2017-06-16 13:42
No it isn't. It works perfectly fine. I can test that far myself.

**Comment by Sandertv** [comment] 2017-06-16 14:18
You might want to test the latest commit. I've thoroughly tested it and it works perfectly now without any errors at all, even with 2 pets fighting eachother.

**Comment by Sandertv** [comment] 2017-06-16 18:14
Should be fixed.

**Closed by Sandertv** 2017-06-16 18:14 UTC
Labels: CATEGORY: Bug, STATUS: Unconfirmed
