### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thisIsHexmor** [BlockHorizons/BlockPets#172] opened 2018-10-28 17:50 UTC
Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "BlockPets-master/src/BlockHorizons/BlockPets/Loader" at line 233

**Comment by Muqsit** [comment] 2018-10-28 21:47
Duplicate of https://github.com/BlockHorizons/BlockPets/issues/169

**Closed by Muqsit** 2018-10-28 21:47 UTC
