### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by Wertzui123** [BlockHorizons/BlockPets#195] opened 2019-03-17 15:31 UTC
[16:25:55] [Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "plugins/BlockPets-4163b4f402494e7ec71b0911c413b8f199904b0e/src/BlockHorizons/BlockPets/Loader" at line 233

**Comment by Muqsit** [comment] 2019-03-17 15:57
Duplicate of #172

**Closed by Muqsit** 2019-03-17 15:57 UTC
