### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Karanztez** [BlockHorizons/BlockPets#191] opened 2019-02-10 11:14 UTC
PocketMine-MP Crash Dump Fri Nov 16 07:06:39 AKST 2018

Error: Call to a member function getServer() on null
File: src/pocketmine/event/entity/EntityDamageByEntityEvent
Line: 72
Type: Error

Code:
[63] }
[64] }
[65]
[66] /
[67] Returns the attacking entity, or null if the attacker has been killed or closed.
[68] 
[69] @return Entity|null
[70] /
[71] public function getDamager() : ?Entity{
[72] return $this->getEntity()->getLevel()->getServer()->findEntity($this->damagerEntityId);
[73] }
[74]
[75] /
[76] @return float
[77] /
[78] public function getKnockBack() : float{
[79] return $this->knockBack;
[80] }
[81]
[82] /**

Backtrace:
#0 src/pocketmine/entity/Living(567): pocketmine\event\entity\EntityDamageByEntityEvent->getDamager()
#1 Pet/src/BlockHorizons/BlockPets/pets/BasePet(328): pocketmine\entity\Living->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
#2 Pet/src/BlockHorizons/BlockPets/pets/IrasciblePet(76): BlockHorizons\BlockPets\pets\BasePet->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
#3 src/pocketmine/level/Explosion(194): BlockHorizons\BlockPets\pets\IrasciblePet->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
#4 src/pocketmine/entity/object/PrimedTNT(112): pocketmine\level\Explosion->explodeB()
#5 src/pocketmine/entity/object/PrimedTNT(97): pocketmine\entity\object\PrimedTNT->explode()
#6 src/pocketmine/entity/Entity(1394): pocketmine\entity\object\PrimedTNT->entityBaseTick(integer 1)
#7 src/pocketmine/level/Level(742): pocketmine\entity\Entity->onUpdate(integer 5246)
#8 src/pocketmine/Server(2370): pocketmine\level\Level->doTick(integer 5246)
#9 src/pocketmine/Server(2519): pocketmine\Server->checkTickUpdates(integer 5246, double 1542384399.3559)
#10 src/pocketmine/Server(2265): pocketmine\Server->tick()
#11 src/pocketmine/Server(2135): pocketmine\Server->tickProcessor()
#12 src/pocketmine/Server(1701): pocketmine\Server->start()
#13 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Administrator\Desktop\Test, string C:\Users\Administrator\Desktop\Test\plugins)
#14 C:/Users/Administrator/Desktop/Test/PocketMine-MP.phar(1): require(string phar://C:/Users/Administrator/Desktop/Test/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
I should correct what happened.cr
I should correct what happened😂
I just load it. And can not fix it, I'm looking for a developer.
sob Please help me
I just laid down TNT​ (pet​ death)​ and my server stopped working.​

**Comment by Muqsit** [comment] 2019-02-10 11:26
Duplicate of #190

**Closed by Muqsit** 2019-02-10 11:26 UTC
