### ISSUE TITLE
suggestion for togglepetcommand

### ISSUE THREAD

**Issue by xkhhv** [BlockHorizons/BlockPets#118] opened 2018-01-16 19:21 UTC
Hello

I have suggestion for togglepetcommand

can you make /togglepet on , /togglpet off , instead of just /togglepet , what i mean is separate on and off , make for everyone its args, i hope you make it.

**Comment by MalakasPlayzMC** [comment] 2018-02-04 08:53
What if the pet is already on and you do /togglepet on

**Comment by Muqsit** [comment] 2018-06-03 22:32
Closing because it's a duplicate of #113

**Closed by Muqsit** 2018-06-03 22:32 UTC
Labels: CATEGORY: Enhancement/Improvement
