### ISSUE TITLE
pet level up

### ISSUE THREAD

**Issue by RubyTemple** [BlockHorizons/BlockPets#173] opened 2018-11-05 21:19 UTC
[22:18:39] [Server thread/CRITICAL]: TypeError:
 "Argument 1 passed to BlockHorizons\BlockPets\
pets\BasePet::addPetLevelPoints() must be of th
e type integer, float given, called in phar:///
root/test2/StartPmmp/plugins/BlockPets_dev-268(
1).phar/src/BlockHorizons/BlockPets/pets/BasePe
t.php on line 297" (EXCEPTION) in "plugins/Bloc
kPets_dev-268(1).phar/src/BlockHorizons/BlockPe
ts/pets/BasePet" at line 370

**Comment by Emis02** [comment] 2018-11-06 08:49
Help?

**Comment by artulloss** [comment] 2018-11-08 01:17
type cast it... use (int) in front of the problematic variable that is a float but needs to be an int.

**Comment by Emis02** [comment] 2018-11-10 13:31
pet doesn't level up

**Comment by ericsimard52** [comment] 2019-01-05 15:30
Same as: https://github.com/BlockHorizons/BlockPets/issues/158

**Comment by lukeeey** [comment] 2021-05-09 23:59
Duplicate of #158

**Closed by lukeeey** 2021-05-09 23:59 UTC
Labels: CATEGORY: Bug, STATUS: Unconfirmed
