### ISSUE TITLE
crash on pet die

### ISSUE THREAD

**Issue by thehexmor** [BlockHorizons/BlockPets#193] opened 2019-02-23 16:44 UTC
[19:50:29] [Server thread/CRITICAL]: Error: "Call to a member function broadcastPacketToViewers() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1210
[19:50:29] [Server thread/DEBUG]: #0 plugins/BlockPets_dev-48.phar/src/BlockHorizons/BlockPets/pets/BasePet(567): pocketmine\entity\Entity->broadcastMovement(boolean )
[19:50:29] [Server thread/DEBUG]: #1 src/pocketmine/entity/Entity(1180): BlockHorizons\BlockPets\pets\BasePet->broadcastMovement(boolean )
[19:50:29] [Server thread/DEBUG]: #2 plugins/BlockPets_dev-48.phar/src/BlockHorizons/BlockPets/pets/WalkingPet(54): pocketmine\entity\Entity->updateMovement()
[19:50:29] [Server thread/DEBUG]: #3 plugins/BlockPets_dev-48.phar/src/BlockHorizons/BlockPets/pets/BasePet(621): BlockHorizons\BlockPets\pets\WalkingPet->doPetUpdates(integer 1204)
[19:50:29] [Server thread/DEBUG]: #4 src/pocketmine/level/Level(840): BlockHorizons\BlockPets\pets\BasePet->onUpdate(integer 1204)
[19:50:29] [Server thread/DEBUG]: #5 src/pocketmine/level/Level(785): pocketmine\level\Level->actuallyDoTick(integer 1204)
[19:50:29] [Server thread/DEBUG]: #6 src/pocketmine/Server(2451): pocketmine\level\Level->doTick(integer 1204)
[19:50:29] [Server thread/DEBUG]: #7 src/pocketmine/Server(2598): pocketmine\Server->checkTickUpdates(integer 1204, double 1550938829.8108)
[19:50:29] [Server thread/DEBUG]: #8 src/pocketmine/Server(2346): pocketmine\Server->tick()
[19:50:29] [Server thread/DEBUG]: #9 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
[19:50:29] [Server thread/DEBUG]: #10 src/pocketmine/Server(1785): pocketmine\Server->start()
[19:50:29] [Server thread/DEBUG]: #11 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Mahan\Desktop\Temorows\, string C:\Users\Mahan\Desktop\Temorows\plugins\)
[19:50:29] [Server thread/DEBUG]: #12 (1): require(string phar://C:/Users/Mahan/Desktop/Temorows/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
[19:50:29] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[19:50:29] [Server thread/EMERGENCY]: Please upload the "C:\Users\Mahan\Desktop\Temorows\crashdumps/Sat_Feb_23-19.50.29-+0330_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Muqsit** [comment] 2019-02-23 16:50
Duplicate of #179

**Closed by Muqsit** 2019-02-23 16:50 UTC
Labels: CATEGORY: Duplicate
