### ISSUE TITLE
Error when attack pet

### ISSUE THREAD

**Issue by MinusMarigold98** [BlockHorizons/BlockPets#205] opened 2019-07-01 09:22 UTC
pet get damage is off but when player attack pet he logout from server
```
[13:49:29] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to BlockHorizons\BlockPets\pets\BasePet::addPetLevelPoints() must be of the type integer, float given, called in phar://C:/Users/asus/Desktop/MCPENetwork-Prison-Server/plugins/BlockPets_dev-269.phar/src/BlockHorizons/BlockPets/pets/BasePet.php on line 297" (EXCEPTION) in "plugins/BlockPets_dev-269.phar/src/BlockHorizons/BlockPets/pets/BasePet" at line 370
[13:49:29] [Server thread/DEBUG]: #0 plugins/BlockPets_dev-269.phar/src/BlockHorizons/BlockPets/pets/BasePet(297): BlockHorizons\BlockPets\pets\BasePet->addPetLevelPoints(double 3)
[13:49:29] [Server thread/DEBUG]: #1 plugins/BlockPets_dev-269.phar/src/BlockHorizons/BlockPets/pets/IrasciblePet(76): BlockHorizons\BlockPets\pets\BasePet->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
[13:49:29] [Server thread/DEBUG]: #2 src/pocketmine/Player(2579): BlockHorizons\BlockPets\pets\IrasciblePet->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
[13:49:29] [Server thread/DEBUG]: #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[13:49:29] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(158): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[13:49:29] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[13:49:30] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[13:49:30] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[13:49:30] [Server thread/DEBUG]: #8 src/pocketmine/Player(3124): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[13:49:30] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[13:49:30] [Server thread/DEBUG]: #10 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 192.168.1.101 50707, object raklib\protocol\EncapsulatedPacket, integer 0)
[13:49:30] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[13:49:30] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[13:49:30] [Server thread/DEBUG]: #13 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[13:49:30] [Server thread/DEBUG]: #14 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[13:49:30] [Server thread/DEBUG]: #15 src/pocketmine/Server(2348): pocketmine\snooze\SleeperHandler->sleepUntil(double 1561972769.9766)
[13:49:30] [Server thread/DEBUG]: #16 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
[13:49:30] [Server thread/DEBUG]: #17 src/pocketmine/Server(1784): pocketmine\Server->start()
[13:49:30] [Server thread/DEBUG]: #18 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] C:\Users\asus\Desktop\MCPENetwork-Prison-Server\, string[56] C:\Users\asus\Desktop\MCPENetwork-Prison-Server\plugins\)
[13:49:30] [Server thread/DEBUG]: #19 (1): require(string[103] phar://C:/Users/asus/Desktop/MCPENetwork-Prison-Server/PocketMine-MP.phar/src/po)
```

**Comment by lukeeey** [comment] 2021-05-09 23:58
Duplicate of #158

**Closed by lukeeey** 2021-05-09 23:59 UTC
