### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by LegoFan48737** [BlockHorizons/BlockPets#198] opened 2019-04-11 19:59 UTC
Using the edition listed on Poggit, it says incompatible API, and that it needs to be updated.
Using the newest dev build, it has this:
`Warning: SQLite3::prepare(): Unable to prepare statement: 1, duplicate column name: Visible in phar:///home/container/plugins/BlockPets.phar/src/BlockHorizons/BlockPets/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 78`

I have no idea what it means, but i figure you can explain, and it can contribute it fixing it and releasing on Poggit :)

**Comment by Muqsit** [comment] 2019-04-12 02:32
Duplicate of #188

**Closed by Muqsit** 2019-04-12 02:32 UTC
Labels: CATEGORY: Duplicate
