### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by optimusprime338** [BlockHorizons/BlockPets#80] opened 2017-09-03 20:43 UTC
Version:- latest 
PocketMine-MP 1.7dev+poggit.1655 
Error:-
```
Error: "Class 'SQLite3' not found" (EXCEPTION) in "BlockPets.phar/src/BlockHorizons/BlockPets/pets/datastorage/SQLiteDataStorer" at line 138
```
on enabling mysql
```
 Error: "Class 'mysqli' not found" (EXCEPTION) in "BlockPets.phar/src/BlockHorizons/BlockPets/pets/datastorage/MySQLDataStorer" at line 135
```

**Comment by Sandertv** [comment] 2017-09-03 21:26
Duplicate of #79, please compile PHP 7.2 with the required extensions.

**Closed by Sandertv** 2017-09-03 21:26 UTC
